<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((2, 2))
b = np.random.sample((2, 2))
a,b

(array([[0.11157873, 0.27640267],
        [0.66388511, 0.49564039]]),
 array([[0.72307264, 0.63158285],
        [0.46333533, 0.30047683]]))

In [3]:
# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
a.ndim,b.ndim

(2, 2)

In [4]:
# Используйте функцию shape, что она вывела?
a.shape,b.shape

((2, 2), (2, 2))

In [5]:
def mult(a, b): #без использования NumPy 
    res = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range (len(b)):
                res[i][j] +=  a[i][k] * b[k][j]
    return res.tolist()

In [6]:
def np_mult(a, b): #с использованием NumPy 
    return np.dot(a, b)

In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 0 ns


In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 7.99 ms


In [9]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.73403692 0.16905968 0.93444589] [0.74216428 0.35887186 0.23740799]


In [11]:
def scalar_product(a, b): # без использования Numpy
    result=0
    for i in range(len(a)):
        result+=a[i]*b[i]
    return result

In [12]:
def np_scalar_product(a,b):#с использованием NumPy 
    return np.dot(a,b)

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 0 ns
Wall time: 0 ns


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [14]:
def np_diag_2k(a):
    result=0
    diag_items = np.diag(a)
    result = diag_items[diag_items%2==0].sum()
    return result

In [15]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))

In [16]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 0 ns


24

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [17]:
def cumsum(A):
    S = np.cumsum(A)
    return S

In [18]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 
%time S2 = cumsum(A)

Wall time: 0 ns


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [19]:
from copy import copy
def np_transformation(X, a=1):
    Y=np.copy(X)
    Y[:,1::2]=a
    Y[:,0::2]=Y[:,::2]**3
    Y[:,::-1]
    return (np.append(arr=X, values=Y, axis=1))

In [20]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

Wall time: 0 ns


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [21]:
import itertools
def np_encode(a):
    return np.array([x for x, y in itertools.groupby(a)]), np.array([len(list(y)) for x, y in itertools.groupby(a)])

In [22]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

Wall time: 0 ns
